services:
  mariadb:
    container_name: mariadb
    image: mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=mypassword
      - MARIADB_DATABASE=pokemon
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - proxy
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    environment:
      - PMA_HOST=mariadb
      - PMA_USER=root
      - PMA_PASSWORD=mypassword
    ports:
      - 8080:80
    networks:
      - proxy

  api:
    container_name: api
    build:
      context: ./backend
    volumes:
      - ./backend:/usr/local/backend
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - mariadb
    networks:
      - proxy
    environment:
      DB_HOST: 'mariadb'
      DB_PORT: '3306'
      DB_DATABASE: 'pokemon'
      DB_USER: 'root'
      DB_PASSWORD: 'mypassword'

  frontend:
    container_name: frontend
    volumes:
      - ./frontend:/usr/local/frontend
    build:
      context: ./frontend
    ports:
      - "3001:3000"
    depends_on:
      - api

volumes:
  db_data:

networks:
  proxy:
    name: proxy